"""
Django settings for xuebatang project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#app文件的根目录设置
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3go2_wpc*vu9x28f_z6wrm0kgijx-4$1#wbxgr^@b(dn-(t4!s'

# SECURITY WARNING: don't run with debug turned on in production!

#404和500，生成环境汇总，必须设置debug=False
#一旦debug改为false，django就不会代管你的静态文件，所以这一要设置一个url处理静态文件
DEBUG =True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'course',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'captcha',
    #分页
    'pure_pagination',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xuebatang.urls'

#users继承自django的User表，要重载AUTH_USER_MODEL
AUTH_USER_MODEL='users.UserProfile'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 添加图片处理器，为了在课程列表中前面加上MEDIA_URL
                'django.template.context_processors.media',
                # 'django.core.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'xuebatang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xubatang',     #数据库的名字
        'USER':'root',          #账号
        'PASSWORD':'',          #密码
        'HOST':'127.0.0.1',      #IP
        'PORT':'3306',          #端口

        #在模型创建数据库表的开发过程中，取消外键的约束
        'UPTIONS':{
            'init_command':"SET foreign_key_checks=0",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE='zh-hans'
# TIME_ZONE = 'UTC'
TIME_ZONE='Asia/Shanghai'
USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ=False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static'),
)

#增加邮箱登录功能时继承CustomBackend
AUTHENTICATION_BACKENDS=(
    'users.views.CustomBackend',
)


#发送邮件
EMAIL_HOST = "smtp.qq.com"  # SMTP服务器主机,必须先开启QQ邮箱的SMTP
EMAIL_PORT = 25             # 端口
EMAIL_HOST_USER = "1580542048@qq.com"       # 邮箱地址
EMAIL_HOST_PASSWORD = "oryoyphricbcfebe"    # 密码
EMAIL_USE_TLS= True
EMAIL_FROM = "1580542048@qq.com"            # 邮箱地址


#设置上传文件的路径,授课机构的显示图片，注意TEMPLATES
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')   #指定根目录


# # # 静态文件,项目上线后
# STATIC_ROOT=os.path.join(BASE_DIR,'/static/')
