# Generated by Django 2.0.7 on 2018-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全球知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
