# Generated by Django 2.0.7 on 2018-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180918_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_tell',
        ),
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
